import Head from 'next/head'
import Image from 'next/image'
import { useCallback, useEffect, useState } from 'react'
import Board from '../components/Board'
import Cell from '../scripts/cell'
import styles from '../styles/Home.module.css'


export default function Home() {
  let [Cells, loadCells] = useState([[new Cell('0','0')]])
  const Chessboard = useCallback(async () => {
    const API_response = await fetch('/api/chessboard').then((response)=>response.json())
    loadCells(API_response.board);
    return API_response
  },[])
  useEffect(() => {
    Chessboard()
  }, [Chessboard])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

          <Board layout={Cells}/>
          
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/MacCrazyman"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {'MacCrazyman'}
        </a>
      </footer>
    </div>
  )
}
